### ISSUE TITLE
Replacing dropzone makes invalid paths

### ISSUE THREAD

**Issue by TravisUNT** [RyMaxim/cotw-mod-builder#7]
When you create mods and tell it to replace the dropzone folder, it creates extra backslashes and thus an invalid path. For example, I created a mod, told it to replace the dropzone folder, and it said "[WinError 3] The system cannot find the path specified: 'F:\\Program Files\\Steam\\Steamapps\\common\\theHunterCotW\\dropzone'"

**Comment by TravisUNT** [comment]
Oh that's funny, github fixed the path... replace every backslash with double backslashes

**Comment by RyMaxim** [comment]
I tested and could only replicate this if I tried to use "Replace" when there wasn't an existing `dropzone` folder in the game folder. The "Load" button should be used the first time you add mods since it will create the `dropzone` folder without first attempting to delete the old one. I'll fix this in the next update so "Replace" won't error out trying to delete a `dropzone` folder that doesn't exist.
